// Seed nutritional_reference table with ~200 common Spanish foods.
// Source values approximated from USDA FoodData Central + BEDCA (Base de Datos Española de Composición de Alimentos).
// All values are per 100g of the food as typically consumed (cooked where applicable).

import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import "dotenv/config";

console.log("DB URL:", process.env.DATABASE_URL);
const prisma = new PrismaClient();

interface FoodEntry {
  name: string;
  category: string;
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatPer100g: number;
  aliases: string[];
}

const FOODS: FoodEntry[] = [
  // ─── CEREALES ──────────────────────────────────────────────────────────────
  {
    name: "Arroz blanco cocido",
    category: "cereales",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28.2,
    fatPer100g: 0.3,
    aliases: ["arroz", "arroz blanco", "arroz cocido"],
  },
  {
    name: "Arroz integral cocido",
    category: "cereales",
    caloriesPer100g: 111,
    proteinPer100g: 2.6,
    carbsPer100g: 23.0,
    fatPer100g: 0.9,
    aliases: ["arroz integral"],
  },
  {
    name: "Pasta cocida",
    category: "cereales",
    caloriesPer100g: 131,
    proteinPer100g: 5.0,
    carbsPer100g: 25.0,
    fatPer100g: 1.1,
    aliases: [
      "pasta",
      "espaguetis",
      "macarrones",
      "spaghetti",
      "fettuccine",
      "penne",
    ],
  },
  {
    name: "Pan blanco",
    category: "cereales",
    caloriesPer100g: 265,
    proteinPer100g: 8.9,
    carbsPer100g: 49.4,
    fatPer100g: 3.2,
    aliases: ["pan", "pan de molde", "baguette"],
  },
  {
    name: "Pan integral",
    category: "cereales",
    caloriesPer100g: 247,
    proteinPer100g: 9.7,
    carbsPer100g: 41.3,
    fatPer100g: 3.4,
    aliases: ["pan integral"],
  },
  {
    name: "Avena cocida",
    category: "cereales",
    caloriesPer100g: 71,
    proteinPer100g: 2.5,
    carbsPer100g: 12.0,
    fatPer100g: 1.5,
    aliases: ["avena", "porridge", "copos de avena cocidos"],
  },
  {
    name: "Copos de avena crudos",
    category: "cereales",
    caloriesPer100g: 389,
    proteinPer100g: 16.9,
    carbsPer100g: 66.3,
    fatPer100g: 6.9,
    aliases: ["copos de avena", "muesli base"],
  },
  {
    name: "Quinoa cocida",
    category: "cereales",
    caloriesPer100g: 120,
    proteinPer100g: 4.4,
    carbsPer100g: 21.3,
    fatPer100g: 1.9,
    aliases: ["quinoa", "quínoa"],
  },
  {
    name: "Cuscús cocido",
    category: "cereales",
    caloriesPer100g: 112,
    proteinPer100g: 3.8,
    carbsPer100g: 23.2,
    fatPer100g: 0.2,
    aliases: ["cuscus", "couscous"],
  },
  {
    name: "Maíz cocido",
    category: "cereales",
    caloriesPer100g: 86,
    proteinPer100g: 3.2,
    carbsPer100g: 18.7,
    fatPer100g: 1.2,
    aliases: ["maiz", "maíz dulce", "elote"],
  },
  {
    name: "Patata cocida",
    category: "cereales",
    caloriesPer100g: 77,
    proteinPer100g: 2.0,
    carbsPer100g: 17.0,
    fatPer100g: 0.1,
    aliases: ["patata", "papa cocida", "potato"],
  },
  {
    name: "Patata frita",
    category: "cereales",
    caloriesPer100g: 312,
    proteinPer100g: 3.4,
    carbsPer100g: 41.4,
    fatPer100g: 14.9,
    aliases: ["patatas fritas", "papas fritas"],
  },
  {
    name: "Boniato cocido",
    category: "cereales",
    caloriesPer100g: 90,
    proteinPer100g: 2.0,
    carbsPer100g: 20.7,
    fatPer100g: 0.1,
    aliases: ["boniato", "batata", "camote"],
  },
  {
    name: "Lentejas cocidas",
    category: "cereales",
    caloriesPer100g: 116,
    proteinPer100g: 9.0,
    carbsPer100g: 20.1,
    fatPer100g: 0.4,
    aliases: ["lentejas"],
  },
  {
    name: "Garbanzos cocidos",
    category: "cereales",
    caloriesPer100g: 164,
    proteinPer100g: 8.9,
    carbsPer100g: 27.4,
    fatPer100g: 2.6,
    aliases: ["garbanzos", "chickpeas"],
  },
  {
    name: "Alubias cocidas",
    category: "cereales",
    caloriesPer100g: 127,
    proteinPer100g: 8.7,
    carbsPer100g: 22.8,
    fatPer100g: 0.5,
    aliases: ["alubias", "judías blancas", "frijoles", "habichuelas"],
  },
  {
    name: "Judías verdes cocidas",
    category: "cereales",
    caloriesPer100g: 35,
    proteinPer100g: 1.9,
    carbsPer100g: 7.9,
    fatPer100g: 0.1,
    aliases: ["judías verdes", "vainitas", "green beans"],
  },

  // ─── PROTEÍNAS (CARNE) ─────────────────────────────────────────────────────
  {
    name: "Pechuga de pollo a la plancha",
    category: "proteinas",
    caloriesPer100g: 165,
    proteinPer100g: 31.0,
    carbsPer100g: 0.0,
    fatPer100g: 3.6,
    aliases: ["pechuga de pollo", "pollo a la plancha", "pollo"],
  },
  {
    name: "Muslo de pollo asado",
    category: "proteinas",
    caloriesPer100g: 209,
    proteinPer100g: 26.0,
    carbsPer100g: 0.0,
    fatPer100g: 11.4,
    aliases: ["muslo de pollo", "contramuslo"],
  },
  {
    name: "Pollo entero asado",
    category: "proteinas",
    caloriesPer100g: 239,
    proteinPer100g: 27.3,
    carbsPer100g: 0.0,
    fatPer100g: 13.6,
    aliases: ["pollo asado", "pollo rostizado"],
  },
  {
    name: "Ternera magra a la plancha",
    category: "proteinas",
    caloriesPer100g: 215,
    proteinPer100g: 26.1,
    carbsPer100g: 0.0,
    fatPer100g: 12.0,
    aliases: ["ternera", "carne de vaca", "bistec"],
  },
  {
    name: "Solomillo de cerdo a la plancha",
    category: "proteinas",
    caloriesPer100g: 143,
    proteinPer100g: 22.3,
    carbsPer100g: 0.0,
    fatPer100g: 5.3,
    aliases: ["solomillo de cerdo", "cerdo magro"],
  },
  {
    name: "Costilla de cerdo asada",
    category: "proteinas",
    caloriesPer100g: 292,
    proteinPer100g: 19.5,
    carbsPer100g: 0.0,
    fatPer100g: 23.5,
    aliases: ["costillas de cerdo"],
  },
  {
    name: "Lomo de cerdo a la plancha",
    category: "proteinas",
    caloriesPer100g: 162,
    proteinPer100g: 25.7,
    carbsPer100g: 0.0,
    fatPer100g: 5.9,
    aliases: ["lomo de cerdo", "chuleta de cerdo"],
  },
  {
    name: "Cordero asado",
    category: "proteinas",
    caloriesPer100g: 258,
    proteinPer100g: 25.5,
    carbsPer100g: 0.0,
    fatPer100g: 16.9,
    aliases: ["cordero", "pierna de cordero"],
  },
  {
    name: "Pavo pechuga a la plancha",
    category: "proteinas",
    caloriesPer100g: 135,
    proteinPer100g: 29.9,
    carbsPer100g: 0.0,
    fatPer100g: 1.0,
    aliases: ["pavo", "pechuga de pavo"],
  },
  {
    name: "Hamburguesa de ternera",
    category: "proteinas",
    caloriesPer100g: 254,
    proteinPer100g: 17.2,
    carbsPer100g: 0.0,
    fatPer100g: 20.3,
    aliases: ["hamburguesa"],
  },

  // ─── PROTEÍNAS (PESCADO) ────────────────────────────────────────────────────
  {
    name: "Salmón a la plancha",
    category: "proteinas",
    caloriesPer100g: 206,
    proteinPer100g: 20.4,
    carbsPer100g: 0.0,
    fatPer100g: 13.4,
    aliases: ["salmón", "salmon"],
  },
  {
    name: "Atún a la plancha",
    category: "proteinas",
    caloriesPer100g: 184,
    proteinPer100g: 29.9,
    carbsPer100g: 0.0,
    fatPer100g: 6.3,
    aliases: ["atún", "tuna"],
  },
  {
    name: "Atún en lata al natural",
    category: "proteinas",
    caloriesPer100g: 116,
    proteinPer100g: 25.5,
    carbsPer100g: 0.0,
    fatPer100g: 1.0,
    aliases: ["atún lata", "atún en conserva"],
  },
  {
    name: "Merluza al horno",
    category: "proteinas",
    caloriesPer100g: 93,
    proteinPer100g: 17.2,
    carbsPer100g: 0.0,
    fatPer100g: 2.5,
    aliases: ["merluza"],
  },
  {
    name: "Bacalao al horno",
    category: "proteinas",
    caloriesPer100g: 105,
    proteinPer100g: 23.0,
    carbsPer100g: 0.0,
    fatPer100g: 0.9,
    aliases: ["bacalao"],
  },
  {
    name: "Dorada al horno",
    category: "proteinas",
    caloriesPer100g: 96,
    proteinPer100g: 17.6,
    carbsPer100g: 0.0,
    fatPer100g: 2.9,
    aliases: ["dorada", "lubina"],
  },
  {
    name: "Lubina al horno",
    category: "proteinas",
    caloriesPer100g: 97,
    proteinPer100g: 18.4,
    carbsPer100g: 0.0,
    fatPer100g: 2.5,
    aliases: ["lubina a la sal"],
  },
  {
    name: "Sardina a la plancha",
    category: "proteinas",
    caloriesPer100g: 208,
    proteinPer100g: 24.6,
    carbsPer100g: 0.0,
    fatPer100g: 11.5,
    aliases: ["sardinas"],
  },
  {
    name: "Boquerón frito",
    category: "proteinas",
    caloriesPer100g: 222,
    proteinPer100g: 17.8,
    carbsPer100g: 6.9,
    fatPer100g: 13.9,
    aliases: ["boquerones", "anchoa frita"],
  },
  {
    name: "Gambas cocidas",
    category: "proteinas",
    caloriesPer100g: 99,
    proteinPer100g: 20.9,
    carbsPer100g: 0.5,
    fatPer100g: 1.1,
    aliases: ["gambas", "langostinos cocidos", "camarones"],
  },
  {
    name: "Calamar a la plancha",
    category: "proteinas",
    caloriesPer100g: 92,
    proteinPer100g: 15.6,
    carbsPer100g: 3.1,
    fatPer100g: 1.4,
    aliases: ["calamar", "sepia", "pulpo"],
  },

  // ─── PROTEÍNAS (EMBUTIDOS) ──────────────────────────────────────────────────
  {
    name: "Jamón serrano",
    category: "proteinas",
    caloriesPer100g: 241,
    proteinPer100g: 30.5,
    carbsPer100g: 0.0,
    fatPer100g: 12.6,
    aliases: ["jamón", "jamón curado", "jamon serrano"],
  },
  {
    name: "Jamón cocido",
    category: "proteinas",
    caloriesPer100g: 107,
    proteinPer100g: 17.5,
    carbsPer100g: 1.8,
    fatPer100g: 3.0,
    aliases: ["jamón de york", "jamón dulce"],
  },
  {
    name: "Chorizo",
    category: "proteinas",
    caloriesPer100g: 455,
    proteinPer100g: 24.1,
    carbsPer100g: 1.9,
    fatPer100g: 38.3,
    aliases: ["chorizo ibérico"],
  },
  {
    name: "Salchichón",
    category: "proteinas",
    caloriesPer100g: 425,
    proteinPer100g: 22.0,
    carbsPer100g: 2.0,
    fatPer100g: 36.0,
    aliases: ["salchichon", "fuet"],
  },
  {
    name: "Salchicha de Frankfurt",
    category: "proteinas",
    caloriesPer100g: 290,
    proteinPer100g: 12.3,
    carbsPer100g: 3.0,
    fatPer100g: 25.3,
    aliases: ["salchicha", "frankfurt", "hotdog"],
  },
  {
    name: "Lomo embuchado",
    category: "proteinas",
    caloriesPer100g: 207,
    proteinPer100g: 33.0,
    carbsPer100g: 0.0,
    fatPer100g: 8.0,
    aliases: ["lomo embuchado"],
  },

  // ─── LÁCTEOS ───────────────────────────────────────────────────────────────
  {
    name: "Leche entera",
    category: "lacteos",
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 3.2,
    aliases: ["leche"],
  },
  {
    name: "Leche desnatada",
    category: "lacteos",
    caloriesPer100g: 35,
    proteinPer100g: 3.4,
    carbsPer100g: 4.9,
    fatPer100g: 0.1,
    aliases: ["leche desnatada", "leche 0%"],
  },
  {
    name: "Yogur natural",
    category: "lacteos",
    caloriesPer100g: 61,
    proteinPer100g: 3.5,
    carbsPer100g: 4.7,
    fatPer100g: 3.3,
    aliases: ["yogur", "yogurt natural"],
  },
  {
    name: "Yogur griego",
    category: "lacteos",
    caloriesPer100g: 97,
    proteinPer100g: 9.0,
    carbsPer100g: 3.6,
    fatPer100g: 5.0,
    aliases: ["yogur griego", "greek yogurt"],
  },
  {
    name: "Queso manchego curado",
    category: "lacteos",
    caloriesPer100g: 392,
    proteinPer100g: 26.0,
    carbsPer100g: 0.5,
    fatPer100g: 32.0,
    aliases: ["queso manchego", "queso curado"],
  },
  {
    name: "Queso fresco",
    category: "lacteos",
    caloriesPer100g: 98,
    proteinPer100g: 11.0,
    carbsPer100g: 3.0,
    fatPer100g: 4.5,
    aliases: ["queso fresco", "queso blanco"],
  },
  {
    name: "Queso en lonchas",
    category: "lacteos",
    caloriesPer100g: 330,
    proteinPer100g: 20.0,
    carbsPer100g: 2.0,
    fatPer100g: 27.0,
    aliases: ["queso lonchas", "queso fundido"],
  },
  {
    name: "Mozzarella",
    category: "lacteos",
    caloriesPer100g: 280,
    proteinPer100g: 22.0,
    carbsPer100g: 2.2,
    fatPer100g: 20.0,
    aliases: ["mozzarella", "mozarela"],
  },
  {
    name: "Nata líquida",
    category: "lacteos",
    caloriesPer100g: 292,
    proteinPer100g: 2.0,
    carbsPer100g: 3.1,
    fatPer100g: 30.0,
    aliases: ["nata", "crema de leche", "heavy cream"],
  },
  {
    name: "Mantequilla",
    category: "grasas",
    caloriesPer100g: 717,
    proteinPer100g: 0.9,
    carbsPer100g: 0.1,
    fatPer100g: 81.1,
    aliases: ["mantequilla", "butter"],
  },
  {
    name: "Huevo cocido",
    category: "proteinas",
    caloriesPer100g: 155,
    proteinPer100g: 13.0,
    carbsPer100g: 1.1,
    fatPer100g: 10.6,
    aliases: ["huevo", "huevo duro", "huevo cocido"],
  },
  {
    name: "Huevo frito",
    category: "proteinas",
    caloriesPer100g: 196,
    proteinPer100g: 13.6,
    carbsPer100g: 0.4,
    fatPer100g: 15.0,
    aliases: ["huevo frito", "huevo a la plancha"],
  },
  {
    name: "Tortilla de patata",
    category: "proteinas",
    caloriesPer100g: 185,
    proteinPer100g: 9.5,
    carbsPer100g: 15.0,
    fatPer100g: 9.7,
    aliases: ["tortilla española", "tortilla de patatas"],
  },

  // ─── FRUTAS ────────────────────────────────────────────────────────────────
  {
    name: "Manzana",
    category: "frutas",
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    aliases: ["manzana", "apple"],
  },
  {
    name: "Plátano",
    category: "frutas",
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatPer100g: 0.3,
    aliases: ["plátano", "banana"],
  },
  {
    name: "Naranja",
    category: "frutas",
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 11.8,
    fatPer100g: 0.1,
    aliases: ["naranja", "orange"],
  },
  {
    name: "Uva",
    category: "frutas",
    caloriesPer100g: 67,
    proteinPer100g: 0.6,
    carbsPer100g: 17.2,
    fatPer100g: 0.4,
    aliases: ["uvas", "grape"],
  },
  {
    name: "Fresa",
    category: "frutas",
    caloriesPer100g: 32,
    proteinPer100g: 0.7,
    carbsPer100g: 7.7,
    fatPer100g: 0.3,
    aliases: ["fresas", "frutillas", "strawberry"],
  },
  {
    name: "Sandía",
    category: "frutas",
    caloriesPer100g: 30,
    proteinPer100g: 0.6,
    carbsPer100g: 7.6,
    fatPer100g: 0.2,
    aliases: ["sandía", "watermelon"],
  },
  {
    name: "Melón",
    category: "frutas",
    caloriesPer100g: 34,
    proteinPer100g: 0.8,
    carbsPer100g: 8.2,
    fatPer100g: 0.2,
    aliases: ["melón", "melon"],
  },
  {
    name: "Pera",
    category: "frutas",
    caloriesPer100g: 57,
    proteinPer100g: 0.4,
    carbsPer100g: 15.2,
    fatPer100g: 0.1,
    aliases: ["pera", "pear"],
  },
  {
    name: "Melocotón",
    category: "frutas",
    caloriesPer100g: 39,
    proteinPer100g: 0.9,
    carbsPer100g: 9.5,
    fatPer100g: 0.3,
    aliases: ["melocotón", "durazno", "peach"],
  },
  {
    name: "Kiwi",
    category: "frutas",
    caloriesPer100g: 61,
    proteinPer100g: 1.1,
    carbsPer100g: 14.7,
    fatPer100g: 0.5,
    aliases: ["kiwi"],
  },
  {
    name: "Mandarina",
    category: "frutas",
    caloriesPer100g: 53,
    proteinPer100g: 0.8,
    carbsPer100g: 13.3,
    fatPer100g: 0.3,
    aliases: ["mandarina", "clementina", "tangerina"],
  },
  {
    name: "Mango",
    category: "frutas",
    caloriesPer100g: 60,
    proteinPer100g: 0.8,
    carbsPer100g: 15.0,
    fatPer100g: 0.4,
    aliases: ["mango"],
  },
  {
    name: "Piña",
    category: "frutas",
    caloriesPer100g: 50,
    proteinPer100g: 0.5,
    carbsPer100g: 13.1,
    fatPer100g: 0.1,
    aliases: ["piña", "ananas", "pineapple"],
  },
  {
    name: "Cereza",
    category: "frutas",
    caloriesPer100g: 63,
    proteinPer100g: 1.1,
    carbsPer100g: 16.0,
    fatPer100g: 0.2,
    aliases: ["cerezas", "cherry"],
  },
  {
    name: "Arándano",
    category: "frutas",
    caloriesPer100g: 57,
    proteinPer100g: 0.7,
    carbsPer100g: 14.5,
    fatPer100g: 0.3,
    aliases: ["arándanos", "blueberry"],
  },
  {
    name: "Aguacate",
    category: "grasas",
    caloriesPer100g: 160,
    proteinPer100g: 2.0,
    carbsPer100g: 8.5,
    fatPer100g: 14.7,
    aliases: ["aguacate", "palta", "avocado"],
  },

  // ─── VERDURAS ──────────────────────────────────────────────────────────────
  {
    name: "Tomate",
    category: "verduras",
    caloriesPer100g: 18,
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatPer100g: 0.2,
    aliases: ["tomate", "tomato"],
  },
  {
    name: "Lechuga",
    category: "verduras",
    caloriesPer100g: 15,
    proteinPer100g: 1.4,
    carbsPer100g: 2.2,
    fatPer100g: 0.2,
    aliases: ["lechuga", "ensalada", "lechugas"],
  },
  {
    name: "Zanahoria cocida",
    category: "verduras",
    caloriesPer100g: 35,
    proteinPer100g: 0.8,
    carbsPer100g: 8.2,
    fatPer100g: 0.2,
    aliases: ["zanahoria", "zanahoria cocida", "carrot"],
  },
  {
    name: "Cebolla cruda",
    category: "verduras",
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbsPer100g: 9.3,
    fatPer100g: 0.1,
    aliases: ["cebolla"],
  },
  {
    name: "Cebolla pochada",
    category: "verduras",
    caloriesPer100g: 115,
    proteinPer100g: 1.4,
    carbsPer100g: 12.0,
    fatPer100g: 7.0,
    aliases: ["cebolla frita", "cebolla caramelizada"],
  },
  {
    name: "Pimiento rojo",
    category: "verduras",
    caloriesPer100g: 31,
    proteinPer100g: 1.0,
    carbsPer100g: 7.3,
    fatPer100g: 0.3,
    aliases: ["pimiento rojo", "red pepper"],
  },
  {
    name: "Pimiento verde",
    category: "verduras",
    caloriesPer100g: 20,
    proteinPer100g: 0.9,
    carbsPer100g: 4.6,
    fatPer100g: 0.2,
    aliases: ["pimiento verde", "green pepper"],
  },
  {
    name: "Calabacín a la plancha",
    category: "verduras",
    caloriesPer100g: 30,
    proteinPer100g: 2.0,
    carbsPer100g: 3.6,
    fatPer100g: 0.7,
    aliases: ["calabacín", "zucchini", "courgette"],
  },
  {
    name: "Berenjena asada",
    category: "verduras",
    caloriesPer100g: 35,
    proteinPer100g: 0.8,
    carbsPer100g: 8.7,
    fatPer100g: 0.2,
    aliases: ["berenjena", "eggplant"],
  },
  {
    name: "Espinaca cocida",
    category: "verduras",
    caloriesPer100g: 23,
    proteinPer100g: 3.0,
    carbsPer100g: 3.8,
    fatPer100g: 0.3,
    aliases: ["espinacas", "spinach"],
  },
  {
    name: "Brócoli cocido",
    category: "verduras",
    caloriesPer100g: 35,
    proteinPer100g: 2.4,
    carbsPer100g: 7.2,
    fatPer100g: 0.4,
    aliases: ["brócoli", "brocoli", "broccoli"],
  },
  {
    name: "Coliflor cocida",
    category: "verduras",
    caloriesPer100g: 25,
    proteinPer100g: 1.9,
    carbsPer100g: 5.0,
    fatPer100g: 0.3,
    aliases: ["coliflor"],
  },
  {
    name: "Champiñón salteado",
    category: "verduras",
    caloriesPer100g: 55,
    proteinPer100g: 3.1,
    carbsPer100g: 6.0,
    fatPer100g: 1.9,
    aliases: ["champiñones", "setas", "mushrooms"],
  },
  {
    name: "Espárragos cocidos",
    category: "verduras",
    caloriesPer100g: 20,
    proteinPer100g: 2.2,
    carbsPer100g: 3.9,
    fatPer100g: 0.1,
    aliases: ["espárragos", "esparragos"],
  },
  {
    name: "Pepino",
    category: "verduras",
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    aliases: ["pepino", "cucumber"],
  },
  {
    name: "Alcachofa cocida",
    category: "verduras",
    caloriesPer100g: 53,
    proteinPer100g: 2.9,
    carbsPer100g: 10.5,
    fatPer100g: 0.2,
    aliases: ["alcachofa", "alcachofas"],
  },
  {
    name: "Puerro cocido",
    category: "verduras",
    caloriesPer100g: 31,
    proteinPer100g: 1.5,
    carbsPer100g: 7.6,
    fatPer100g: 0.2,
    aliases: ["puerro"],
  },
  {
    name: "Col rizada cocida",
    category: "verduras",
    caloriesPer100g: 28,
    proteinPer100g: 1.9,
    carbsPer100g: 5.6,
    fatPer100g: 0.5,
    aliases: ["kale", "col rizada", "berza"],
  },
  {
    name: "Remolacha cocida",
    category: "verduras",
    caloriesPer100g: 44,
    proteinPer100g: 1.7,
    carbsPer100g: 9.6,
    fatPer100g: 0.2,
    aliases: ["remolacha", "betabel", "beet"],
  },
  {
    name: "Apio crudo",
    category: "verduras",
    caloriesPer100g: 16,
    proteinPer100g: 0.7,
    carbsPer100g: 3.0,
    fatPer100g: 0.2,
    aliases: ["apio"],
  },

  // ─── GRASAS Y SALSAS ────────────────────────────────────────────────────────
  {
    name: "Aceite de oliva",
    category: "grasas",
    caloriesPer100g: 884,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatPer100g: 100.0,
    aliases: ["aceite de oliva", "aove", "olive oil"],
  },
  {
    name: "Aceite de girasol",
    category: "grasas",
    caloriesPer100g: 884,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatPer100g: 100.0,
    aliases: ["aceite de girasol", "aceite vegetal"],
  },
  {
    name: "Mayonesa",
    category: "salsas",
    caloriesPer100g: 680,
    proteinPer100g: 1.3,
    carbsPer100g: 2.7,
    fatPer100g: 74.9,
    aliases: ["mayonesa", "mayonaise", "alioli"],
  },
  {
    name: "Tomate frito",
    category: "salsas",
    caloriesPer100g: 65,
    proteinPer100g: 1.5,
    carbsPer100g: 10.5,
    fatPer100g: 2.0,
    aliases: ["tomate frito", "salsa de tomate", "tomato sauce"],
  },
  {
    name: "Salsa bechamel",
    category: "salsas",
    caloriesPer100g: 100,
    proteinPer100g: 3.0,
    carbsPer100g: 9.0,
    fatPer100g: 5.8,
    aliases: ["bechamel"],
  },
  {
    name: "Ketchup",
    category: "salsas",
    caloriesPer100g: 97,
    proteinPer100g: 1.7,
    carbsPer100g: 23.5,
    fatPer100g: 0.1,
    aliases: ["ketchup", "catsup"],
  },
  {
    name: "Mostaza",
    category: "salsas",
    caloriesPer100g: 66,
    proteinPer100g: 4.4,
    carbsPer100g: 5.3,
    fatPer100g: 3.3,
    aliases: ["mostaza"],
  },
  {
    name: "Salsa de soja",
    category: "salsas",
    caloriesPer100g: 53,
    proteinPer100g: 5.2,
    carbsPer100g: 4.9,
    fatPer100g: 0.1,
    aliases: ["salsa de soja", "soy sauce"],
  },
  {
    name: "Hummus",
    category: "salsas",
    caloriesPer100g: 177,
    proteinPer100g: 7.9,
    carbsPer100g: 20.1,
    fatPer100g: 8.6,
    aliases: ["hummus"],
  },
  {
    name: "Guacamole",
    category: "salsas",
    caloriesPer100g: 152,
    proteinPer100g: 2.0,
    carbsPer100g: 8.5,
    fatPer100g: 13.5,
    aliases: ["guacamole"],
  },
  {
    name: "Aceitunas verdes",
    category: "grasas",
    caloriesPer100g: 145,
    proteinPer100g: 1.0,
    carbsPer100g: 3.8,
    fatPer100g: 15.3,
    aliases: ["aceitunas", "olivas", "olives"],
  },
  {
    name: "Nueces",
    category: "grasas",
    caloriesPer100g: 654,
    proteinPer100g: 15.2,
    carbsPer100g: 13.7,
    fatPer100g: 65.2,
    aliases: ["nueces", "walnuts"],
  },
  {
    name: "Almendras",
    category: "grasas",
    caloriesPer100g: 579,
    proteinPer100g: 21.2,
    carbsPer100g: 21.7,
    fatPer100g: 49.9,
    aliases: ["almendras", "almonds"],
  },
  {
    name: "Cacahuetes",
    category: "grasas",
    caloriesPer100g: 567,
    proteinPer100g: 25.8,
    carbsPer100g: 16.1,
    fatPer100g: 49.2,
    aliases: ["cacahuetes", "maní", "peanuts"],
  },
  {
    name: "Mantequilla de cacahuete",
    category: "grasas",
    caloriesPer100g: 589,
    proteinPer100g: 25.1,
    carbsPer100g: 20.0,
    fatPer100g: 50.4,
    aliases: ["mantequilla de maní", "peanut butter"],
  },

  // ─── OTROS ─────────────────────────────────────────────────────────────────
  {
    name: "Azúcar blanco",
    category: "otros",
    caloriesPer100g: 387,
    proteinPer100g: 0.0,
    carbsPer100g: 99.8,
    fatPer100g: 0.0,
    aliases: ["azúcar", "sugar"],
  },
  {
    name: "Miel",
    category: "otros",
    caloriesPer100g: 304,
    proteinPer100g: 0.3,
    carbsPer100g: 82.4,
    fatPer100g: 0.0,
    aliases: ["miel", "honey"],
  },
  {
    name: "Chocolate negro 70%",
    category: "otros",
    caloriesPer100g: 598,
    proteinPer100g: 7.8,
    carbsPer100g: 45.9,
    fatPer100g: 42.6,
    aliases: ["chocolate negro", "dark chocolate"],
  },
  {
    name: "Chocolate con leche",
    category: "otros",
    caloriesPer100g: 535,
    proteinPer100g: 7.7,
    carbsPer100g: 59.4,
    fatPer100g: 29.7,
    aliases: ["chocolate", "chocolate con leche"],
  },
  {
    name: "Coca-Cola",
    category: "otros",
    caloriesPer100g: 42,
    proteinPer100g: 0.0,
    carbsPer100g: 10.6,
    fatPer100g: 0.0,
    aliases: ["coca-cola", "refresco de cola"],
  },
  {
    name: "Zumo de naranja",
    category: "otros",
    caloriesPer100g: 45,
    proteinPer100g: 0.7,
    carbsPer100g: 10.4,
    fatPer100g: 0.2,
    aliases: ["zumo de naranja", "jugo de naranja", "orange juice"],
  },
  {
    name: "Café solo",
    category: "otros",
    caloriesPer100g: 2,
    proteinPer100g: 0.1,
    carbsPer100g: 0.0,
    fatPer100g: 0.0,
    aliases: ["café", "cafe", "espresso"],
  },
  {
    name: "Cerveza",
    category: "otros",
    caloriesPer100g: 43,
    proteinPer100g: 0.5,
    carbsPer100g: 3.6,
    fatPer100g: 0.0,
    aliases: ["cerveza", "beer"],
  },
  {
    name: "Vino tinto",
    category: "otros",
    caloriesPer100g: 85,
    proteinPer100g: 0.1,
    carbsPer100g: 2.6,
    fatPer100g: 0.0,
    aliases: ["vino tinto", "vino"],
  },

  // ─── PLATOS TÍPICOS ESPAÑOLES ──────────────────────────────────────────────
  {
    name: "Gazpacho",
    category: "verduras",
    caloriesPer100g: 30,
    proteinPer100g: 0.8,
    carbsPer100g: 5.5,
    fatPer100g: 0.7,
    aliases: ["gazpacho"],
  },
  {
    name: "Paella mixta",
    category: "cereales",
    caloriesPer100g: 148,
    proteinPer100g: 9.2,
    carbsPer100g: 19.5,
    fatPer100g: 3.7,
    aliases: ["paella", "arroz con pollo y mariscos"],
  },
  {
    name: "Cocido madrileño",
    category: "proteinas",
    caloriesPer100g: 130,
    proteinPer100g: 8.5,
    carbsPer100g: 11.0,
    fatPer100g: 5.5,
    aliases: ["cocido", "puchero"],
  },
  {
    name: "Fabada asturiana",
    category: "cereales",
    caloriesPer100g: 155,
    proteinPer100g: 9.5,
    carbsPer100g: 15.0,
    fatPer100g: 6.5,
    aliases: ["fabada"],
  },
  {
    name: "Pisto manchego",
    category: "verduras",
    caloriesPer100g: 65,
    proteinPer100g: 1.5,
    carbsPer100g: 7.5,
    fatPer100g: 3.5,
    aliases: ["pisto", "ratatouille"],
  },
  {
    name: "Croquetas de jamón",
    category: "otros",
    caloriesPer100g: 210,
    proteinPer100g: 8.5,
    carbsPer100g: 20.5,
    fatPer100g: 10.8,
    aliases: ["croquetas"],
  },
  {
    name: "Patatas bravas",
    category: "cereales",
    caloriesPer100g: 185,
    proteinPer100g: 2.5,
    carbsPer100g: 25.0,
    fatPer100g: 8.5,
    aliases: ["patatas bravas"],
  },
  {
    name: "Pan con tomate",
    category: "cereales",
    caloriesPer100g: 165,
    proteinPer100g: 4.5,
    carbsPer100g: 27.0,
    fatPer100g: 4.5,
    aliases: ["pan tumaca", "pa amb tomàquet"],
  },
  {
    name: "Ensalada mixta",
    category: "verduras",
    caloriesPer100g: 25,
    proteinPer100g: 1.2,
    carbsPer100g: 4.0,
    fatPer100g: 0.5,
    aliases: ["ensalada", "ensalada verde"],
  },
  {
    name: "Ensalada cesar",
    category: "verduras",
    caloriesPer100g: 120,
    proteinPer100g: 6.0,
    carbsPer100g: 8.0,
    fatPer100g: 7.5,
    aliases: ["ensalada César", "caesar salad"],
  },
  {
    name: "Pizza margherita",
    category: "cereales",
    caloriesPer100g: 250,
    proteinPer100g: 10.0,
    carbsPer100g: 33.0,
    fatPer100g: 8.5,
    aliases: ["pizza"],
  },
  {
    name: "Sopa de fideos",
    category: "cereales",
    caloriesPer100g: 62,
    proteinPer100g: 3.0,
    carbsPer100g: 10.0,
    fatPer100g: 1.0,
    aliases: ["sopa de fideos", "sopa de pasta"],
  },
  {
    name: "Crema de verduras",
    category: "verduras",
    caloriesPer100g: 55,
    proteinPer100g: 1.5,
    carbsPer100g: 8.5,
    fatPer100g: 1.8,
    aliases: ["crema de verduras", "puré de verduras"],
  },
  {
    name: "Bocadillo de jamón",
    category: "cereales",
    caloriesPer100g: 230,
    proteinPer100g: 12.0,
    carbsPer100g: 28.0,
    fatPer100g: 7.5,
    aliases: ["bocadillo de jamón", "sandwich de jamón"],
  },
];

async function main(): Promise<void> {
  console.log("Seeding nutritional_reference table...");

  let inserted = 0;
  let skipped = 0;

  for (const food of FOODS) {
    const existing = await prisma.nutritionalReference.findFirst({
      where: { name: { equals: food.name, mode: "insensitive" } },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.nutritionalReference.create({
      data: {
        id: crypto.randomUUID(),
        name: food.name,
        category: food.category,
        caloriesPer100g: food.caloriesPer100g,
        proteinPer100g: food.proteinPer100g,
        carbsPer100g: food.carbsPer100g,
        fatPer100g: food.fatPer100g,
        aliases: food.aliases,
      },
    });
    inserted++;
  }

  console.log(
    `Done. Inserted: ${inserted}, Skipped (already exists): ${skipped}`,
  );

  // Feature 001 — demo user so sign-in is exercisable in development.
  const demoEmail = "demo@calories.app";
  const demoPasswordHash = await bcrypt.hash("Demo1234!", 12);
  await prisma.user.upsert({
    where: { email: demoEmail },
    update: { passwordHash: demoPasswordHash },
    create: { email: demoEmail, passwordHash: demoPasswordHash },
  });
  console.log(`Seeded demo user: ${demoEmail}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
